language: java

jobs:
  include:
    - stage: "Frontend"
      name: "Lint"
      before_install:
        - nvm install 8.9
      install:
        - cd frontend/sentiment-dashboard
        - npm install -g @angular/cli
        - npm install
      script:
        - ng lint
    - name: "Build"
      before_install:
        - nvm install 8.9
      install:
        - cd frontend/sentiment-dashboard
        - npm install -g @angular/cli
        - npm install
      script:
        - ng build --prod
    - name: "Test"
      before_install:
        - nvm install 8.9
      install:
        - cd frontend/sentiment-dashboard
        - npm install -g @angular/cli
        - npm install
      script:
        - ng test --browsers ChromeHeadlessNoSandbox --watch=false
    - stage: "Backend"
      name: "Java/Spring Lint"
      install:
        - cd backend/main
      script:
        - mvn checkstyle:check
    - name: "Java/Spring Build & Test"
      env:
        - FUNCTION_NAME=hello
      install:
        - cd backend/main
      script:
        - mvn clean
        - mvn package
    - name: "Node.js (Reviews API) Lint"
      before_install:
        - nvm install 8.9
      install:
        - cd backend/reviews
        - npm install
      script:
        - npm run-script lint
    - name: "Node.js (Reviews API) Test"
      before_install:
        - nvm install 8.9
      install:
        - cd backend/reviews
        - npm install
      script:
        - npm test
