service: sentiment-dashboard
provider:
  name: aws
  stage: ${opt:stage}
  region: us-east-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:BatchWriteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.tableName}*"
    - Effect: Allow
      Action:
        - comprehend:BatchDetectSentiment
        - comprehend:BatchDetectKeyPhrases
      Resource: "*"
    - Effect: Allow
      Action:
        - ssm:GetParameter
        - ssm:PutParameter
      Resource:
        - 'Fn::Join':
          - ':'
          -
            - 'arn:aws:ssm'
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'

plugins:
    - serverless-finch

custom:
  tableName: 'appReviewsTable-${self:provider.stage}'
  
  client:
    bucketName: ${self:service}-client-${self:provider.stage}
    distributionFolder: ../frontend/sentiment-dashboard/dist/sentiment-dashboard

package:
  individually: true
  exclude:
    - ./**

functions:
  main:
    runtime: java8
    timeout: 10
    memorySize: 2048
    handler: sentiment.Handler
    package:
      artifact: main/target/sentiment-BETA-aws.jar
    environment:
      FUNCTION_NAME: stats
      TABLE_NAME: ${self:custom.tableName}
      DEPLOY_REGION: ${self:provider.region}
      STAGE: ${self:provider.stage}
    events:
      - http:
          method: post
          path: stats
          cors: true
      - http:
          method: get
          path: apps
          cors: true
      - http:
          method: post
          path: settings/apps
          cors: true
          authorizer: arn:aws:cognito-idp:us-east-2:948594532470:userpool/us-east-2_R99catdY3
      - http:
          method: post
          path: settings/get
          cors: true
          authorizer: arn:aws:cognito-idp:us-east-2:948594532470:userpool/us-east-2_R99catdY3
      - http:
          method: post
          path: settings/set
          cors: true
          authorizer: arn:aws:cognito-idp:us-east-2:948594532470:userpool/us-east-2_R99catdY3
  reviews:
    runtime: nodejs8.10
    timeout: 60
    handler: reviews/handler.handler
    package:
      include:
        - reviews/**
    environment:
      TABLE_NAME: ${self:custom.tableName}
      DEPLOY_REGION: ${self:provider.region}
    events:
      - http:
          method: any
          path: reviews

resources:
  Resources:
    appReviewsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: appIdStore
            AttributeType: S
          - AttributeName: reviewHash
            AttributeType: S
          - AttributeName: date
            AttributeType: S
          - AttributeName: sentiment
            AttributeType: S
        KeySchema:
          - AttributeName: appIdStore
            KeyType: HASH
          - AttributeName: reviewHash
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        GlobalSecondaryIndexes:
          - IndexName: sentiment
            KeySchema:
              - AttributeName: appIdStore
                KeyType: HASH
              - AttributeName: sentiment
                KeyType: RANGE
            Projection:
              NonKeyAttributes:
                - sentimentScore
                - keywords
              ProjectionType: INCLUDE
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
          - IndexName: date
            KeySchema:
              - AttributeName: appIdStore
                KeyType: HASH
              - AttributeName: date
                KeyType: RANGE
            Projection:
              NonKeyAttributes:
                - reviewHash
                - version
                - sentiment
                - sentimentScore
                - keywords
              ProjectionType: INCLUDE
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5

