service: sentiment-dashboard
provider:
  name: aws
  stage: ${opt:stage}
  region: us-east-2

package:
  individually: true

functions:
  nlp:
    runtime: python3.6
    handler: nlp/handler.hello
    events:
      - http:
          method: get
          path: nlp
  main:
    runtime: java8
    timeout: 10
    handler: sentiment.Handler
    package:
      artifact: main/target/sentiment-ALPHA-aws.jar
    events:
      - http:
          method: any
          path: main
    environment:
      FUNCTION_NAME: hello
  reviews:
    runtime: nodejs8.10
    handler: reviews/handler.hello
    events:
      - http:
          method: any
          path: reviews

resources:
  Resources:
    rawReviewsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: rawReviewsTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
