service: sentiment-dashboard
provider:
  name: aws
  stage: ${opt:stage}
  region: us-east-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.tableName}*"

plugins:
    - serverless-finch
    - serverless-python-requirements

custom:
  tableName: 'appReviewsTable-${self:provider.stage}'
  
  client:
    bucketName: ${self:service}-client-${self:provider.stage}
    distributionFolder: ../frontend/sentiment-dashboard/dist/sentiment-dashboard

package:
  individually: true
  exclude:
    - ./**

functions:
  nlp:
    runtime: python3.6
    timeout: 10
    handler: nlp/handler.main
    package:
      include:
        - nlp/**
        - sentiment/**
        - tokenizers/**
    events:
      - http:
          method: post
          path: nlp
    environment:
      STAGE: ${self:provider.stage}
      TABLE_NAME: ${self:custom.tableName}
      DEPLOY_REGION: ${self:provider.region}
  main:
    runtime: java8
    timeout: 10
    memorySize: 2048
    handler: sentiment.Handler
    package:
      artifact: main/target/sentiment-ALPHA-aws.jar
    environment:
      FUNCTION_NAME: stats
      TABLE_NAME: ${self:custom.tableName}
      DEPLOY_REGION: ${self:provider.region}
    events:
      - http:
          method: post
          path: stats
          cors: true
      - http:
          method: get
          path: apps
          cors: true
  reviews:
    runtime: nodejs8.10
    timeout: 30
    handler: reviews/handler.handler
    package:
      include:
        - reviews/**
    environment:
      STAGE: ${self:provider.stage}
      TABLE_NAME: ${self:custom.tableName}
      DEPLOY_REGION: ${self:provider.region}
    events:
      - http:
          method: any
          path: reviews

resources:
  Resources:
    appReviewsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: appIdStore
            AttributeType: S
          - AttributeName: reviewHash
            AttributeType: S
          - AttributeName: date
            AttributeType: S
          - AttributeName: compSentiment
            AttributeType: N
        KeySchema:
          - AttributeName: appIdStore
            KeyType: HASH
          - AttributeName: reviewHash
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        GlobalSecondaryIndexes:
          - IndexName: sentiment
            KeySchema:
              - AttributeName: appIdStore
                KeyType: HASH
              - AttributeName: compSentiment
                KeyType: RANGE
            Projection:
              NonKeyAttributes:
                - posSentiment
                - neuSentiment
                - negSentiment
              ProjectionType: INCLUDE
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
          - IndexName: date
            KeySchema:
              - AttributeName: appIdStore
                KeyType: HASH
              - AttributeName: date
                KeyType: RANGE
            Projection:
              NonKeyAttributes:
                - reviewHash
                - version
              ProjectionType: INCLUDE
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
