service: sentiment-dashboard
provider:
  name: aws
  stage: ${opt:stage}
  region: us-east-2

package:
  individually: true

functions:
  nlp:
    runtime: python3.6
    handler: nlp/handler.hello
    events:
      - http:
          method: get
          path: nlp
  main:
    runtime: java8
    timeout: 10
    memorySize: 2048
    handler: sentiment.Handler
    package:
      artifact: main/target/sentiment-ALPHA-aws.jar
    events:
      - http:
          method: any
          path: main
          cors: true
    environment:
      FUNCTION_NAME: hello
  reviews:
    runtime: nodejs8.10
    handler: reviews/handler.handler
    events:
      - http:
          method: any
          path: reviews

resources:
  Resources:
    appReviewsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: appReviewsTable-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: appIdStore
            AttributeType: S
          - AttributeName: versionDate
            AttributeType: S
          - AttributeName: compSentiment
            AttributeType: N
        KeySchema:
          - AttributeName: appIdStore
            KeyType: HASH
          - AttributeName: versionDate
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        GlobalSecondaryIndexes:
          - IndexName: sentiment
            KeySchema:
              - AttributeName: appIdStore
                KeyType: HASH
              - AttributeName: compSentiment
                KeyType: RANGE
            Projection:
              NonKeyAttributes:
                - posSentiment
                - neuSentiment
                - negSentiment
              ProjectionType: INCLUDE
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
